apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway-config
  namespace: istio-system
spec:
  selector:
    istio: ingress  # Bate com o label que acabamos de confirmar
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"