apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml

helmCharts:
  - name: argo-cd
    releaseName: argocd
    version: 5.51.6 # Ou a versão que preferir
    repo: https://argoproj.github.io/argo-helm
    namespace: argocd
    valuesFile: values.yaml