# =====================================================
# Argo CD - values.yaml (Configuração HA)
# =====================================================

argo-cd:
  global:
    # Resolve o problema do Service não achar os Pods (Labels de Identidade)
    additionalLabels:
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/part-of: argocd
    
    topologySpreadConstraints: &commonConstraints
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/part-of: argocd

  server:
    replicas: 2
    topologySpreadConstraints: *commonConstraints
    service:
      type: ClusterIP # Interno, pois o Nginx no IP .201 fará o roteamento
    extraArgs:
      - --staticassets
      - --server-base-href=/
      - --insecure # Permite que o Ingress Nginx faça o offload do SSL se necessário

  repoServer:
    replicas: 2
    topologySpreadConstraints: *commonConstraints

  controller:
    replicas: 2

  redis-ha:
    enabled: false # Para 2 nodes, Redis single é mais estável