ingress-nginx:
  controller:
    replicaCount: 1 # Para laboratório, 1 é suficiente
    
    # Configurações do Serviço para pegar o IP .201
    service:
      annotations:
        # Aqui conectamos com o nome que você deu no pool-nginx.yaml do MetalLB
        metallb.universe.tf/address-pool: nginx-pool
      loadBalancerIP: 192.168.56.201
      type: LoadBalancer

    # Habilita o SSL Passthrough para o ArgoCD funcionar corretamente
    extraArgs:
      enable-ssl-passthrough: ""

    # Garante que o Ingress use a classe 'nginx'
    ingressClassResource:
      name: nginx
      enabled: true
      default: true