apiVersion: metallb.io/v1beta1  # <-- Ajustado aqui
kind: IPAddressPool
metadata:
  name: nginx-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.56.201-192.168.56.201
  autoAssign: false # Mudei para true para facilitar seu primeiro teste