apiVersion: metallb.io/v1beta1  # <-- Ajustado para a versão atual
kind: IPAddressPool
metadata:
  name: istio-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.56.200-192.168.56.200
  autoAssign: false # Permite que o serviço do Istio encontre este IP