apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloudops
  namespace: argocd
spec:
  description: Projeto base para gerenciamento GitOps da plataforma
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
